web:
  build: .
  command: python main.py
  ports:
    - "8080:8080"
  volumes:
    - .:/todo
  links:
    - db
tests:
  build: .
  command: python tests.py
  ports:
    - "8081:8081"
  volumes:
    - .:/todo
  links:
    - db
db:
  image: mongo:3.0.2